name: Fooman M2 CI-CD

on: push

jobs:
    integration:
        name: Integration Testing
        runs-on: ubuntu-latest
        container:
            image: magento/magento-cloud-docker-php:7.3-cli-1.0
            env:
                ENABLE_SENDMAIL: true

        services:
            mysql:
                image: quay.io/warden/mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: 123123q
                    MYSQL_DATABASE: magento_integration_tests
                ports:
                    - 3306
                options: >-
                    --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
                    --mount type=tmpfs,destination=/var/lib/mysql
            rabbitmq:
                image: quay.io/warden/rabbitmq:3.7
                ports:
                    - 5672
                options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            -   uses: actions/checkout@v2
                name: Checkout files

            -   name: Get composer cache directory
                id: composer-cache
                run: "echo \"::set-output name=dir::$(composer config cache-dir)\""

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Setup Composer Access
                run: composer config -a -g http-basic.repo.magento.com ${{ secrets.REPO_MAGENTO_USERNAME }} ${{ secrets.REPO_MAGENTO_PASSWORD }}

            -   name: Composer install
                run: composer install --no-interaction --no-progress --no-suggest

            -   name: Run Checkout Integration Tests
                if: github.ref == 'refs/heads/master'
                run: cd dev/tests/integration && $GITHUB_WORKSPACE/vendor/bin/phpunit -c $GITHUB_WORKSPACE/dev/tests/integration/phpunit.stage.xml

            -   name: Run Subset of Integration Tests including Checkout
                if: startsWith(github.ref, 'refs/tags/')
                run: cd dev/tests/integration && $GITHUB_WORKSPACE/vendor/bin/phpunit -c $GITHUB_WORKSPACE/dev/tests/integration/phpunit.prod.xml

    deploy-to-staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        needs: [integration]
        if: github.ref == 'refs/heads/master'
        steps:
            -   uses: actions/checkout@v2
                name: Checkout files

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: 7.3
                    extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip

            -   name: Get composer cache directory
                id: composer-cache
                run: "echo \"::set-output name=dir::$(composer config cache-dir)\""

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Setup Composer Access
                run: composer config -a -g http-basic.repo.magento.com ${{ secrets.REPO_MAGENTO_USERNAME }} ${{ secrets.REPO_MAGENTO_PASSWORD }}

            -   name: Composer install
                run: composer install --no-interaction --no-progress --no-suggest

            -   name: Setup Deployer
                uses: atymic/deployer-php-action@master
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                    ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

            -   name: Build deployment artifact
                run: dep build

            -   name: Deploy Artifact to Staging
                run: dep deploy-artifact stage

    deploy-to-prod:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: [integration]
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            -   uses: actions/checkout@v2
                name: Checkout files

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: 7.3
                    extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip

            -   name: Get composer cache directory
                id: composer-cache
                run: "echo \"::set-output name=dir::$(composer config cache-dir)\""

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Setup Composer Access
                run: composer config -a -g http-basic.repo.magento.com ${{ secrets.REPO_MAGENTO_USERNAME }} ${{ secrets.REPO_MAGENTO_PASSWORD }}

            -   name: Composer install
                run: composer install --no-interaction --no-progress --no-suggest

            -   name: Setup Deployer
                uses: atymic/deployer-php-action@master
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                    ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

            -   name: Build deployment artifact
                run: dep build

            -   name: Deploy Artifact to Production
                run: dep deploy-artifact prod
